# https://meta.icos-cp.eu/sparqlclient

PREFIX cpst: <http://meta.icos-cp.eu/ontologies/stationentry/>
SELECT
(str(?s) AS ?id)
(IF(bound(?lat), str(?lat), "?") AS ?latstr)
(IF(bound(?lon), str(?lon), "?") AS ?lonstr)
(IF(bound(?spatRef), str(?spatRef), "?") AS ?geoJson)
(IF(bound(?locationDesc), str(?locationDesc), "?") AS ?location)
(REPLACE(str(?class),"http://meta.icos-cp.eu/ontologies/stationentry/", "") AS ?themeShort)
(REPLACE(str(?class),"http://meta.icos-cp.eu/ontologies/stationentry/", "") AS ?Theme)
(IF(bound(?country), str(?country), "?") AS ?Country)
(str(?sName) AS ?Short_name)
(str(?lName) AS ?Long_name)
(GROUP_CONCAT(?piLname; separator=";") AS ?PI_names)
(IF(bound(?siteType), str(?siteType), "?") AS ?Site_type)
(IF(bound(?elevationAboveSea), str(?elevationAboveSea), "?") AS ?Elevation_AS)
(IF(bound(?elevationAboveGround), str(?elevationAboveGround), "?") AS ?Elevation_AG)
(IF(bound(?stationClass), str(?stationClass), "?") AS ?Station_class)
(IF(bound(?stationKind), str(?stationKind), "?") AS ?Station_kind)
(IF(bound(?preIcosMeasurements), str(?preIcosMeasurements), "?") AS ?Pre_ICOS_meassurement)
(IF(bound(?operationalDateEstimate), str(?operationalDateEstimate), "?") AS ?Operational_date_estimate)
(IF(bound(?isOperational), str(?isOperational), "?") AS ?Is_operational)
(IF(bound(?fundingForConstruction), str(?fundingForConstruction), "?") AS ?Funding_for_construction)
FROM <http://meta.icos-cp.eu/resources/stationentry/>
WHERE {
?s a ?class .
OPTIONAL{?s cpst:hasLat ?lat . ?s cpst:hasLon ?lon } .
OPTIONAL{?s cpst:hasSpatialReference ?spatRef } .
OPTIONAL{?s cpst:hasLocationDescription ?locationDesc } .
OPTIONAL{?s cpst:hasCountry ?country } .
?s cpst:hasShortName ?sName .
?s cpst:hasLongName ?lName .
?s cpst:hasPi ?pi .
OPTIONAL{?pi cpst:hasFirstName ?piFname } .
?pi cpst:hasLastName ?piLname .
OPTIONAL{?s cpst:hasSiteType ?siteType } .
OPTIONAL{?s cpst:hasElevationAboveSea ?elevationAboveSea } .
OPTIONAL{?s cpst:hasElevationAboveGround ?elevationAboveGround } .
OPTIONAL{?s cpst:hasStationClass ?stationClass } .
OPTIONAL{?s cpst:hasStationKind ?stationKind } .
OPTIONAL{?s cpst:hasPreIcosMeasurements ?preIcosMeasurements } .
OPTIONAL{?s cpst:hasOperationalDateEstimate ?operationalDateEstimate } .
OPTIONAL{?s cpst:isAlreadyOperational ?isOperational } .
OPTIONAL{?s cpst:hasFundingForConstruction ?fundingForConstruction } .
}
GROUP BY ?s ?lat ?lon ?spatRef ?locationDesc ?class ?country ?sName ?lName ?siteType ?elevationAboveSea
 ?elevationAboveGround ?stationClass ?stationKind ?preIcosMeasurements ?operationalDateEstimate ?isOperational ?fundingForConstruction
